apiVersion: blueprints.cloud.google.com/v1alpha3
kind: ResourceHierarchy
metadata:
  name: root-hierarchy
  namespace: hierarchy # kpt-set: ${namespace}
  annotations:
    config.kubernetes.io/local-config: "true"
    configmanagement.gke.io/managed: disabled
spec:
  config:
    - dev:
        $subtree: environment
    - prod:
        $subtree: environment
  parentRef:
    external: "123456789012" # kpt-set: ${org-id}
  subtrees:
    environment:
      - retail:
          - apps
          - data_and_analysis
      - finance:
          - commercial
          - retail
