apiVersion: blueprints.cloud.google.com/v1alpha3
kind: ResourceHierarchy
metadata:
  name: root-hierarchy
  namespace: hierarchy # kpt-set: ${namespace}
  annotations:
    config.kubernetes.io/local-config: "true"
    configmanagement.gke.io/managed: disabled
spec:
  config:
    - retail:
        $subtree: environments
    - finance:
        $subtree: environments
  parentRef:
    external: "123456789012" # kpt-set: ${org-id}
  subtrees:
    environments:
      - dev
      - prod
      - qa
